spring:
  application:
    name: cse-cc-runner
  rabbitmq:
    host: localhost
    port: 5672
    username: gridcapa
    password: gridcapa
    template:
      reply-timeout: 2400000
  cloud:
    stream:
      bindings:
        task-status-update:
          binder: rabbit
          destination: task-status-updated

logback:
  amqp:
    exchange: task-manager-events
    routing-key: "#"

rao-runner-server:
  amqp:
    client-app-id: cse-cc-runner  # should be overridden with value of app name
    queue-name: rao-request-queue

minio-adapter:
  bucket: gridcapa
  base-path: ""
  access-key: gridcapa
  secret-key: gridcapa
  url: http://minio:9000

cse-cc-runner:
  zone-id: "Europe/Paris"
  xnodes:
    file-path: /home/farao/xnodes/xnodes.xml
  combined-ras:
    file-path: /home/farao/combinedRAs/combinedRAs.json
  pisa:
    link1:
      node-fr: FFG.IL12
      node-it: FFG.IL11
      fictive-lines:
        - FFG.IL12 FFG.IL11 1
        - FFG.IL12 FFG.IL11 2
    link2:
      node-fr: FFG.IL14
      node-it: FFG.IL13
      fictive-lines:
        - FFG.IL14 FFG.IL13 1
        - FFG.IL14 FFG.IL13 2
  bindings:
    request:
      destination: cse-request
      routing-key: "#"
      group: cse-idcc-runner
    response:
      destination: cse-response
      expiration: 60000
  whitelist:
    - http://minio:9000/
    - http://localhost:9000/
outputs:
  initial-cgm: INITIAL_CGM
  final-cgm: FINAL_CGM
  ttc-res: TTC_RES